

ARCH_FLAG = 
CC=cc
CFLAGS   =  -I${HOME}/include -I. -g ${ARCH_FLAG}
LDFLAGS  =  -L${HOME}/lib  ${ARCH_FLAG}


OBJ = disk.o master.o slave.o steuerfile.o commands.o stuff.o

SRC = ${OBJ:.o=.c}

disk_io: ${OBJ}
	$(CC) ${LDFLAGS} -o disk_io ${OBJ}

${OBJ}: disk_io.h

lint:
	lint -Xarch=v9  -DSOLARIS_7 -Nlevel  ${SRC}

install: disk_io
	if [ ! -d ${HOME}/bin ]; then mkdir ${HOME}/bin; fi
	cp disk_io ${HOME}/bin
	chmod 711  ${HOME}/bin/disk_io

clean:
	rm -f disk_io *.o 

